app/urls.py
from django.urls import path

from .views import api, web

app_name='app'
urlpatterns = [
    path('', web.TimeLineView.as_view(), name="timeline"),
    path('slideshow', web.SlideShowView.as_view(), name="slideshow"),
    path('callback', api.callback, name="callback"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/app/')),
    path('app/', include('app.urls')),
]

app/models.py
from django.db import models

from datetime import datetime

from cloudinary.models import CloudinaryField


class Photo(models.Model):
    image = CloudinaryField('image')
    created_at = models.DateTimeField(default=datetime.now)

    def __str__(self):
        try:
            public_id = self.image.public_id
        except AttributeError:
            public_id = ''
        return "Photo <%s>" % public_id

api/views.py
import os, tempfile
from django.http import HttpResponse, HttpResponseForbidden

from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import (MessageEvent, TextMessage, TextSendMessage,
                            ImageMessage, )

from cloudinary.uploader import upload
# from cloudinary.utils import cloudinary_url, private_download_url
from config.settings import CHANNEL_ACCESS_TOKEN, LINE_ACCESS_SECRET
from .models import PhotoUrl

line_bot_api = LineBotApi(channel_access_token=CHANNEL_ACCESS_TOKEN)
handler = WebhookHandler(channel_secret=LINE_ACCESS_SECRET)


def index(request):
    return HttpResponse("This is photo sharing api.")


def callback(request):
    signature = request.META['HTTP_X_LINE_SIGNATURE']
    body = request.body.decode('utf-8')

    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        HttpResponseForbidden()

    return HttpResponse('OK', status=200)


@handler.add(MessageEvent, message=TextMessage)
def handle_text_message(event):
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text='reply_message')
    )


@handler.add(MessageEvent, message=[ImageMessage])
def handle_image_message(event):
    if isinstance(event.message, ImageMessage):
        ext = 'jpg'
    else:
        line_bot_api.reply_message(
            event.reply_token,
            TextSendMessage(text='invalid message')
        )
        return

    message_content = line_bot_api.get_message_content(event.message.id)
    with tempfile.NamedTemporaryFile(prefix=ext + '-', delete=True) as tf:
        for chunk in message_content.iter_content():
            tf.write(chunk)

        upload_result = upload(tf.name, type="private")

        if "error" in upload_result:
            error_text = 'invalid image'
            line_bot_api.reply_message(
                event.reply_token,
                TextSendMessage(text=error_text)
            )
            return

        PhotoUrl.objects.create(cloud_id=upload_result['public_id'])
        # private_download_url(upload_result['public_id'], format=ext)

        line_bot_api.reply_message(
            event.reply_token,
            TextSendMessage(text='save image')
        )

app/views/api.py
import os, tempfile
from django.http import HttpResponse, HttpResponseForbidden

from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import (MessageEvent, TextMessage, TextSendMessage,
                            ImageMessage, )

from cloudinary.uploader import upload_image
from config.settings import CHANNEL_ACCESS_TOKEN, LINE_ACCESS_SECRET
from app.models import Photo

line_bot_api = LineBotApi(channel_access_token=CHANNEL_ACCESS_TOKEN)
handler = WebhookHandler(channel_secret=LINE_ACCESS_SECRET)


def callback(request):
    signature = request.META['HTTP_X_LINE_SIGNATURE']
    body = request.body.decode('utf-8')

    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        HttpResponseForbidden()

    return HttpResponse('OK', status=200)


@handler.add(MessageEvent, message=TextMessage)
def handle_text_message(event):
    line_bot_api.reply_message(
        event.reply_token,
        TextSendMessage(text='reply_message')
    )


@handler.add(MessageEvent, message=[ImageMessage])
def handle_image_message(event):
    if isinstance(event.message, ImageMessage):
        ext = 'jpg'
    else:
        line_bot_api.reply_message(
            event.reply_token,
            TextSendMessage(text='invalid message')
        )
        return

    message_content = line_bot_api.get_message_content(event.message.id)
    with tempfile.NamedTemporaryFile(prefix=ext + '-', delete=True) as tf:
        for chunk in message_content.iter_content():
            tf.write(chunk)

        image = upload_image(tf.name)
        Photo.objects.create(image=image)

        line_bot_api.reply_message(
            event.reply_token,
            TextSendMessage(text='save image')
        )

app/views/web.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView

from app.models import Photo


class TimeLineView(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'app/timeline.html'
    queryset = Photo.objects.order_by('created_at').reverse().all()


class SlideShowView(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'app/slideshow.html'
    queryset = Photo.objects.order_by('created_at').reverse().all()

app/templates/app/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  {% load bootstrap4 %}
  {% load static %}
  {% load cloudinary %}

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>photo-sharing {% block title %}{% endblock %}</title>

  {% bootstrap_css %}
  <link href="{% static 'app/css/base.css' %}" rel="stylesheet">
  {% block extra_css %}{% endblock %}
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'app:timeline' %}">
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
         viewBox="0 0 24 24" fill="none" stroke="currentColor"
         stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
         class="mr-2">
      <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
      <circle cx="12" cy="13" r="4"></circle>
    </svg>
    <strong>photo-sharing</strong>
  </a>

  <div class="collapse navbar-collapse" id="navbarsLmManagement">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#"
           id="ledger" data-toggle="dropdown" aria-haspopup="true"
           aria-expanded="false">モード</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url 'app:timeline' %}">
            タイムライン
          </a>
          <a class="dropdown-item" href="{% url 'app:slideshow' %}">
            スライドショー
          </a>
        </div>
      </li>
    </ul>
  </div>
</nav>

{% bootstrap_messages %}
{% block content %}{% endblock %}

{% bootstrap_javascript jquery=True %}
{% cloudinary_includes %}
{% cloudinary_js_config %}
{% block extra_script %}{% endblock %}
{{ form.media }}
</body>
</html>

app/templates/app/slideshow.html
{% extends 'app/base.html' %}
{% load bootstrap4 %}

{% block title %}- slideshow{% endblock %}

{% block extra_css %}
  {% load static %}
  {% load cloudinary %}
  <link href="{% static 'app/css/slideshow.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <div id="slideshow" class="slideshow">
    {% for photo in photo_list %}
      {% cloudinary photo.image class="image col-sm-12" %}
    {% endfor %}
  </div>
{% endblock %}

{% block extra_script %}
  <script type='text/javascript'>
      $(function () {
          var img = $("#slideshow").children("img"),
              num = img.length,
              count = 0,
              interval = 10000;

          img.eq(0).addClass("show");

          var images = document.getElementsByClassName('image');

          for (var i = 0; i < images.length; i++) {
              var w = images[i].clientWidth;
              var h = images[i].clientHeight;

              var width_ratio = document.body.clientWidth / w;
              var height_ratio = document.body.clientHeight / h;
              var min_ratio = Math.min(width_ratio, height_ratio);
              images[i].style.width = w * min_ratio;
              images[i].style.height = h * min_ratio;
          }

          setTimeout(slide, interval);

          function slide() {
              img.eq(count).removeClass("show");
              count++;
              if (count >= num) {
                  location.reload(true);
              }
              img.eq(count).addClass("show");
              setTimeout(slide, interval);
          }
      });
  </script>
{% endblock %}

app/templates/app/timeline.html
{% extends 'app/base.html' %}
{% load bootstrap4 %}
{% load cloudinary %}

{% block title %}- timeline{% endblock %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        {% for photo in photo_list %}
          <div class="col-md-4">
            <a class="card mb-4 shadow-sm" href="{{ photo.image.url }}">
              {% cloudinary photo.image height=300 crop="scale" %}
            </a>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <script type='text/javascript'>
      (function () {
          var t = setInterval(function () {
              location.reload(true);
          }, 10000);
      })();
  </script>
{% endblock %}

templates/html/app/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  {% load bootstrap4 %}

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>photo-sharing {% block title %}{% endblock %}</title>

  {% bootstrap_css %}
</head>

<body>
<header>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a class="navbar-brand" href="{% url 'app:timeline' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
             viewBox="0 0 24 24" fill="none" stroke="currentColor"
             stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
             class="mr-2">
          <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
          <circle cx="12" cy="13" r="4"></circle>
        </svg>
        <strong>photo-sharing</strong>
      </a>
    </div>
  </div>
</header>

<main role="main" class="container margin-header">
  {% bootstrap_messages %}
  {% block content %}{% endblock %}
</main>

{% bootstrap_javascript jquery=True %}
{{ form.media }}
</body>
</html>

templates/html/app/index.html
{% extends 'html/app/base.html' %}
{% load bootstrap4 %}

{% block title %}- index{% endblock %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">

        {% for photo in photo_list %}
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <img class="card-img-top"
                   src={{ photo.image.url }}
                           alt={{ photo.public_id }}>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>
  <script type='text/javascript'>
      (function () {
          var t = setInterval(function () {
              location.reload(true);
          }, 10000);
      })();
  </script>
{% endblock %}

templates/html/app/timeline.html
{% extends 'html/app/base.html' %}
{% load bootstrap4 %}

{% block title %}- timeline{% endblock %}

{% block content %}
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">

        {% for photo in photo_list %}
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <img class="card-img-top"
                   src={{ photo.image.url }}
                           alt={{ photo.public_id }}>
            </div>
          </div>
        {% endfor %}

      </div>
    </div>
  </div>
  <script type='text/javascript'>
      (function () {
          var t = setInterval(function () {
              location.reload(true);
          }, 10000);
      })();
  </script>
{% endblock %}